import PinModel from '../models/pin';

export class GetVote {
    constructor(){
        this.getvote;
    }

    getvote(req, res, next){
        return res.status(200).json({
            message: 'Welcome to the voting platform'
        });
    }
}

/**
 * Authenticate the Voter with the Pin generated by the admin of 
 * the voter and the voter name, if the authentication process is successful,
 * then the user can be redirected to the voting page
 */
export class AuthVoter {
    constructor(){
        this.loginVoter;
    }

    loginVoter(req, res,next){
        const VoterDetails = {
            pin: req.body.pin,
            name: req.body.name
        }

        PinModel.findOne({voter_pin: VoterDetails.pin}).then( result => {
            if( result.voter_name === VoterDetails.name){

            }
        }).catch( err => {
            if(!err.statusCode){
                err.statusCode = 500;
            }
            next(err);
        })
    }
}